args:
  method: langevin
  # lr: 1e-3
  langevin_reg_param: 1e-4
  kernel_reg_param: None
  kernel_args:
    sigma: None
  noise_param: 1
  likl_param: 1
  kernel_param: None
  prior_kernel_param: None
